framework:
    cache:
        default_redis_provider: 'redis://redis'
        pools:
            data_cache:
                adapter: cache.adapter.redis

when@test:
    framework:
        cache:
            pools:
                data_cache:
                    adapter: cache.adapter.array