services:
  php:
    image: dfossacecchi/php-8.2-fpm:1.4
    build:
      context: ./docker/php
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    user: 'www-data'
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
  nginx:
    image: dfossacecchi/nginx:1.0
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - "63791:6379"
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  mysql_data:

